name: minimal
description: A minimalistic Flutter website template for blogs and portfolios.
version: 1.5.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  responsive_framework: ^1.1.1
  # Uncomment to build standalone project.
  #  responsive_framework: ^1.0.0
  google_fonts: ^5.1.0
  animations: ^2.0.8
  loading_gifs: ^0.3.0
  firebase_storage: ^11.6.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  fluttertoast: ^8.2.4
  photo_view: ^0.14.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/Minimal-Logo.png"
  image_path_ios: "assets/Minimal-Logo-iOS.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/Minimal-Logo-Adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - images/